package com.biocircular.compostaje.controller;
import com.biocircular.compostaje.dto.*; import com.biocircular.compostaje.entity.EstadoLote; import com.biocircular.compostaje.service.CompostajeService; import jakarta.validation.Valid; import org.springframework.data.domain.*; import org.springframework.data.web.PageableDefault; import org.springframework.http.*; import org.springframework.web.bind.annotation.*; import java.util.*;
@RestController @RequestMapping("/api") public class CompostajeController { private final CompostajeService s; public CompostajeController(CompostajeService x){s=x;}
 @GetMapping("/tipos-residuos") List<Responses.TipoResiduo> tipos(){return s.tipos();} @PostMapping("/tipos-residuos") @ResponseStatus(HttpStatus.CREATED) Responses.TipoResiduo tipo(@Valid @RequestBody Requests.TipoResiduo r){return s.crearTipo(r);}@PutMapping("/tipos-residuos/{id}") Responses.TipoResiduo tipoPut(@PathVariable UUID id,@Valid @RequestBody Requests.TipoResiduo r){return s.actualizarTipo(id,r);}@DeleteMapping("/tipos-residuos/{id}") @ResponseStatus(HttpStatus.NO_CONTENT) void tipoDel(@PathVariable UUID id){s.desactivarTipo(id);}
 @GetMapping("/ingresos-residuos") Page<Responses.Ingreso> ingresos(@RequestParam(required=false) UUID tipoResiduoId,@PageableDefault(size=20,sort="fechaHora",direction=Sort.Direction.DESC) Pageable p){return s.listarIngresos(tipoResiduoId,p);}@PostMapping("/ingresos-residuos") @ResponseStatus(HttpStatus.CREATED) Responses.Lote ingreso(@Valid @RequestBody Requests.IngresoResiduo r){return s.registrarIngreso(r);}
 @GetMapping("/lotes") Page<Responses.Lote> lotes(@RequestParam(required=false) EstadoLote estado,@PageableDefault(size=20,sort="fechaInicio",direction=Sort.Direction.DESC) Pageable p){return s.listarLotes(estado,p);}@PostMapping("/lotes") @ResponseStatus(HttpStatus.CREATED) Responses.Lote lote(@Valid @RequestBody Requests.Lote r){return s.crearLote(r);}@GetMapping("/lotes/{id}") Responses.Lote loteGet(@PathVariable UUID id){return s.lote(id);}@PatchMapping("/lotes/{id}/cancelar") Responses.Lote cancelar(@PathVariable UUID id){return s.cancelarLote(id);}
 @GetMapping("/lotes/{id}/etapas") List<Responses.Etapa> etapas(@PathVariable UUID id){return s.trazabilidad(id).etapas();}@PostMapping("/lotes/{id}/etapas") @ResponseStatus(HttpStatus.CREATED) Responses.Etapa etapa(@PathVariable UUID id,@Valid @RequestBody Requests.Etapa r){return s.agregarEtapa(id,r);}@PatchMapping("/etapas-lote/{id}/finalizar") Responses.Etapa finalizar(@PathVariable UUID id){return s.finalizarEtapa(id);}
 @GetMapping("/lotes/{id}/observaciones") List<Responses.Observacion> observaciones(@PathVariable UUID id){return s.trazabilidad(id).observaciones();}@PostMapping("/lotes/{id}/observaciones") @ResponseStatus(HttpStatus.CREATED) Responses.Observacion observar(@PathVariable UUID id,@Valid @RequestBody Requests.Observacion r){return s.observar(id,r);}
 @GetMapping("/compost") List<Responses.Compost> compost(){return s.compost();}@PostMapping("/compost") @ResponseStatus(HttpStatus.CREATED) Responses.Compost producir(@Valid @RequestBody Requests.Produccion r){return s.producir(r);}@GetMapping("/compost/{id}/inventario") Responses.Inventario inventario(@PathVariable UUID id){return s.inventario(id);}@PostMapping("/inventario") @ResponseStatus(HttpStatus.CREATED) Responses.Movimiento mover(@Valid @RequestBody Requests.Movimiento r){return s.mover(r);}
 @GetMapping("/trazabilidad/{id}") Responses.Trazabilidad trazabilidad(@PathVariable UUID id){return s.trazabilidad(id);}@GetMapping("/dashboard") Responses.Dashboard dashboard(){return s.dashboard();}
}
