package com.biocircular.reportes.service;
import com.biocircular.reportes.dto.*; import org.apache.pdfbox.pdmodel.*; import org.apache.pdfbox.pdmodel.font.PDType1Font; import org.apache.pdfbox.pdmodel.font.Standard14Fonts; import org.apache.poi.xssf.usermodel.XSSFWorkbook; import org.springframework.beans.factory.annotation.Value; import org.springframework.http.*; import org.springframework.stereotype.Service; import org.springframework.web.client.RestTemplate; import java.io.*; import java.math.*; import java.time.*; import java.util.*;
@Service public class ReportService { private final RestTemplate http; private final String gestion,compostaje,auditoria; public ReportService(RestTemplate h,@Value("${app.gestion-url}")String g,@Value("${app.compostaje-url}")String c,@Value("${app.auditoria-url}")String a){http=h;gestion=g;compostaje=c;auditoria=a;}
 public List<Map<String,Object>> data(String type,ReportFilterDto f){String path=switch(type.toLowerCase()){case "clientes"->"/api/clientes";case "recolecciones"->"/api/recolecciones";case "rutas"->"/api/rutas";case "compostaje"->"/api/lotes";case "inventario"->"/api/compost";default->throw new IllegalArgumentException("Tipo de reporte no soportado");}; String base=(type.equalsIgnoreCase("compostaje")||type.equalsIgnoreCase("inventario"))?compostaje:gestion; try{ResponseEntity<Object> r=http.getForEntity(base+path,Object.class);return rows(r.getBody());}catch(Exception e){throw new IllegalStateException("No fue posible consultar "+type+" mediante REST",e);} }
 @SuppressWarnings("unchecked") private List<Map<String,Object>> rows(Object x){if(x instanceof List<?> l)return l.stream().filter(Map.class::isInstance).map(v->(Map<String,Object>)v).toList();if(x instanceof Map<?,?> m&&m.get("content") instanceof List<?> l)return l.stream().filter(Map.class::isInstance).map(v->(Map<String,Object>)v).toList();return List.of();}
 public DashboardDto dashboard(ReportFilterDto f){List<Map<String,Object>> rec=data("recolecciones",f), lot=data("compostaje",f), cli=data("clientes",f), rut=data("rutas",f);BigDecimal kg=sum(rec,"pesoKg","peso","cantidadKg"), compost=sum(data("inventario",f),"cantidadKg");long dias=Math.max(1,Optional.ofNullable(f.fechaDesde()).map(d->java.time.temporal.ChronoUnit.DAYS.between(d,Optional.ofNullable(f.fechaHasta()).orElse(LocalDate.now()))+1).orElse(1L));audit("CONSULTA_DASHBOARD");return new DashboardDto(kg.longValue(),compost,cli.size(),rut.size(),lot.size(),0,0,kg.divide(BigDecimal.valueOf(dias),2,RoundingMode.HALF_UP).doubleValue(),cli.isEmpty()?"0 kg CO2eq por cliente":compost.divide(BigDecimal.valueOf(cli.size()),2,RoundingMode.HALF_UP)+" kg compost por cliente");}
 private BigDecimal sum(List<Map<String,Object>> rows,String... keys){return rows.stream().flatMap(m->Arrays.stream(keys).map(m::get)).filter(Objects::nonNull).map(x->{try{return new BigDecimal(x.toString());}catch(Exception e){return BigDecimal.ZERO;}}).reduce(BigDecimal.ZERO,BigDecimal::add);}
 public byte[] pdf(String type,ReportFilterDto f){List<Map<String,Object>> rows=data(type,f);try(PDDocument d=new PDDocument();ByteArrayOutputStream out=new ByteArrayOutputStream()){PDPage p=new PDPage();d.addPage(p);try(PDPageContentStream c=new PDPageContentStream(d,p)){c.beginText();c.setFont(new PDType1Font(Standard14Fonts.FontName.HELVETICA_BOLD),16);c.newLineAtOffset(50,760);c.showText("BioCircular - Reporte de "+type);c.setFont(new PDType1Font(Standard14Fonts.FontName.HELVETICA),9);c.newLineAtOffset(0,-20);c.showText("Generado: "+OffsetDateTime.now()+" | Registros: "+rows.size());int y=700;for(Map<String,Object> r:rows.subList(0,Math.min(rows.size(),30))){c.newLineAtOffset(0,y-740);c.showText(r.toString().replaceAll("[\\r\\n]"," ").substring(0,Math.min(105,r.toString().length())));y-=18;}c.endText();}d.save(out);audit("GENERACION_PDF");return out.toByteArray();}catch(IOException e){throw new IllegalStateException("No se pudo generar el PDF",e);}}
 public byte[] excel(String type,ReportFilterDto f){List<Map<String,Object>> rows=data(type,f);try(XSSFWorkbook wb=new XSSFWorkbook();ByteArrayOutputStream out=new ByteArrayOutputStream()){var sh=wb.createSheet("Reporte");var title=sh.createRow(0);title.createCell(0).setCellValue("BioCircular - "+type+" - "+LocalDate.now());Set<String> cols=new LinkedHashSet<>();rows.forEach(m->cols.addAll(m.keySet()));var h=sh.createRow(2);int col=0;for(String k:cols)h.createCell(col++).setCellValue(k);int n=3;for(Map<String,Object> r:rows){var row=sh.createRow(n++);col=0;for(String k:cols)row.createCell(col++).setCellValue(Objects.toString(r.get(k),""));}for(int i=0;i<cols.size();i++)sh.autoSizeColumn(i);wb.write(out);audit("GENERACION_EXCEL");return out.toByteArray();}catch(IOException e){throw new IllegalStateException("No se pudo generar el Excel",e);}}
 private void audit(String a){try{http.postForEntity(auditoria+"/api/auditorias/eventos",Map.of("accion",a,"recurso","REPORTE"),Void.class);}catch(Exception ignored){}}
}
