server:
  port: 8080
spring:
  datasource:
    url: "${SPRING_DATASOURCE_URL:jdbc:postgresql://auth-db:5432/auth_db}"
    username: "${SPRING_DATASOURCE_USERNAME:biocircular}"
    password: "${SPRING_DATASOURCE_PASSWORD:biocircular_local_dev}"
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
app:
  jwt-secret: "${JWT_SECRET:development_only_change_before_deployment_2026}"
  jwt-expiration: "${JWT_EXPIRATION:3600000}"
