server:
  port: 8080
spring:
  datasource:
    url: "${SPRING_DATASOURCE_URL:jdbc:postgresql://auditoria-db:5432/auditoria_db}"
    username: "${SPRING_DATASOURCE_USERNAME:biocircular}"
    password: "${SPRING_DATASOURCE_PASSWORD:biocircular_local_dev}"
  jpa:
    hibernate:
      ddl-auto: validate
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
