import 'zone.js';
import { CommonModule } from '@angular/common';
import { HttpClient, HttpErrorResponse, provideHttpClient, withInterceptors } from '@angular/common/http';
import { Component, computed, inject, signal } from '@angular/core';
import { FormBuilder, FormsModule, ReactiveFormsModule, Validators } from '@angular/forms';
import { Router, RouterLink, RouterLinkActive, RouterOutlet, Routes, provideRouter } from '@angular/router';
import { authInterceptor } from './app/auth';
import { bootstrapApplication } from '@angular/platform-browser';

type Field = { key: string; label: string; type?: 'text' | 'email' | 'number' | 'date' | 'select' | 'textarea'; options?: string[] };
type ModuleConfig = { title: string; subtitle: string; endpoint: string; fields: Field[]; columns: string[]; sample: Record<string, string | number>[] };

const MODULES: Record<string, ModuleConfig> = {
  clientes: { title: 'Clientes', subtitle: 'Administre datos de contacto y aporte ambiental.', endpoint: 'clientes', columns: ['nombre', 'identificacion', 'tipo', 'sector', 'telefono'], fields: [{key:'nombre',label:'Nombre o razón social'}, {key:'identificacion',label:'Identificación'}, {key:'tipo',label:'Tipo de cliente',type:'select',options:['Residencial','Comercial']}, {key:'direccion',label:'Dirección'}, {key:'sector',label:'Sector'}, {key:'telefono',label:'Teléfono'}, {key:'correo',label:'Correo electrónico',type:'email'}], sample: [{nombre:'Eco Mercado Central',identificacion:'1790012345001',tipo:'Comercial',sector:'Centro',telefono:'099 123 4567'}, {nombre:'María López',identificacion:'0923456789',tipo:'Residencial',sector:'Norte',telefono:'098 765 4321'}] },
  contenedores: { title: 'Contenedores', subtitle: 'Asigne y controle los contenedores entregados.', endpoint: 'contenedores', columns: ['codigo', 'cliente', 'capacidad', 'estado', 'fechaEntrega'], fields: [{key:'codigo',label:'Código'}, {key:'cliente',label:'Cliente'}, {key:'capacidad',label:'Capacidad (L)',type:'number'}, {key:'estado',label:'Estado',type:'select',options:['Operativo','Mantenimiento','Retirado']}, {key:'fechaEntrega',label:'Fecha de entrega',type:'date'}], sample: [{codigo:'CNT-001',cliente:'Eco Mercado Central',capacidad:120,estado:'Operativo',fechaEntrega:'2026-07-20'}, {codigo:'CNT-002',cliente:'María López',capacidad:60,estado:'Operativo',fechaEntrega:'2026-07-22'}] },
  rutas: { title: 'Rutas y recolecciones', subtitle: 'Planifique recorridos, paradas, operadores y vehículo.', endpoint: 'rutas', columns: ['nombre', 'sector', 'fecha', 'operador', 'vehiculo'], fields: [{key:'nombre',label:'Nombre de ruta'}, {key:'sector',label:'Sector'}, {key:'fecha',label:'Fecha programada',type:'date'}, {key:'frecuencia',label:'Frecuencia',type:'select',options:['Diaria','Semanal','Quincenal']}, {key:'operador',label:'Operador responsable'}, {key:'vehiculo',label:'Vehículo'}, {key:'horario',label:'Horario'}], sample: [{nombre:'Ruta Norte 01',sector:'Norte',fecha:'2026-08-01',operador:'Carlos Pérez',vehiculo:'PBA-1234'}, {nombre:'Ruta Centro 02',sector:'Centro',fecha:'2026-08-01',operador:'Ana Mena',vehiculo:'PBC-4082'}] },
  recolecciones: { title: 'Recolecciones', subtitle: 'Registre visitas, cantidades y novedades del servicio.', endpoint: 'recolecciones', columns: ['fecha', 'cliente', 'operador', 'cantidad', 'novedad'], fields: [{key:'fecha',label:'Fecha',type:'date'}, {key:'cliente',label:'Cliente'}, {key:'operador',label:'Operador'}, {key:'cantidad',label:'Cantidad (kg)',type:'number'}, {key:'unidad',label:'Unidad',type:'select',options:['kg','toneladas','litros']}, {key:'novedad',label:'Novedad / observación',type:'textarea'}], sample: [{fecha:'2026-08-01',cliente:'Eco Mercado Central',operador:'Carlos Pérez',cantidad:184,novedad:'Sin novedades'}, {fecha:'2026-08-01',cliente:'María López',operador:'Ana Mena',cantidad:28,novedad:'Contenedor revisado'}] },
  vehiculos: { title: 'Flota y mantenimiento', subtitle: 'Mantenga vehículos operativos y consulte sus mantenimientos.', endpoint: 'vehiculos', columns: ['placa', 'modelo', 'capacidad', 'estado', 'ultimoMantenimiento'], fields: [{key:'placa',label:'Placa'}, {key:'modelo',label:'Modelo'}, {key:'capacidad',label:'Capacidad (kg)',type:'number'}, {key:'estado',label:'Estado',type:'select',options:['Operativo','Mantenimiento','Inactivo']}, {key:'ultimoMantenimiento',label:'Último mantenimiento',type:'date'}], sample: [{placa:'PBA-1234',modelo:'Hino 300',capacidad:3500,estado:'Operativo',ultimoMantenimiento:'2026-07-10'}, {placa:'PBC-4082',modelo:'Chevrolet NHR',capacidad:2500,estado:'Mantenimiento',ultimoMantenimiento:'2026-07-28'}] },
  operadores: { title: 'Usuarios y operadores', subtitle: 'Gestione cuentas, cargos y permisos de acceso.', endpoint: 'operadores', columns: ['nombre', 'correo', 'cargo', 'rol', 'estado'], fields: [{key:'nombre',label:'Nombres completos'}, {key:'correo',label:'Correo',type:'email'}, {key:'cargo',label:'Cargo'}, {key:'rol',label:'Rol',type:'select',options:['Administrador','Supervisor','Operador','Cliente']}, {key:'estado',label:'Estado',type:'select',options:['Activo','Inactivo']}], sample: [{nombre:'Carlos Pérez',correo:'carlos@biocircular.ec',cargo:'Operador',rol:'Operador',estado:'Activo'}, {nombre:'Ana Mena',correo:'ana@biocircular.ec',cargo:'Supervisora',rol:'Supervisor',estado:'Activo'}] },
  lotes: { title: 'Lotes y etapas', subtitle: 'Controle el estado, las etapas y el cierre de cada lote.', endpoint: 'lotes', columns: ['codigo', 'fechaInicio', 'estado', 'etapa', 'peso'], fields: [{key:'codigo',label:'Código de lote'}, {key:'fechaInicio',label:'Fecha de inicio',type:'date'}, {key:'peso',label:'Peso recibido (kg)',type:'number'}, {key:'etapa',label:'Etapa',type:'select',options:['Recepción','Descomposición','Maduración','Finalizado']}, {key:'estado',label:'Estado',type:'select',options:['Activo','Finalizado','Cancelado']}, {key:'responsable',label:'Responsable'}], sample: [{codigo:'LOT-2026-014',fechaInicio:'2026-07-10',estado:'Activo',etapa:'Maduración',peso:1220}, {codigo:'LOT-2026-015',fechaInicio:'2026-07-24',estado:'Activo',etapa:'Descomposición',peso:980}] },
  residuos: { title: 'Tipos de residuos', subtitle: 'Configure los residuos orgánicos autorizados.', endpoint: 'tipos-residuos', columns: ['nombre', 'descripcion', 'estado'], fields: [{key:'nombre',label:'Nombre'}, {key:'descripcion',label:'Descripción',type:'textarea'}, {key:'estado',label:'Estado',type:'select',options:['Activo','Inactivo']}], sample: [{nombre:'Restos vegetales',descripcion:'Hojas, poda y material vegetal',estado:'Activo'}, {nombre:'Residuos de alimentos',descripcion:'Frutas y verduras sin empaque',estado:'Activo'}] },
  inventario: { title: 'Inventario de compost', subtitle: 'Consulte disponibilidad y movimientos del compost terminado.', endpoint: 'compost', columns: ['lote', 'cantidad', 'fechaProduccion', 'disponibilidad'], fields: [{key:'lote',label:'Lote'}, {key:'cantidad',label:'Cantidad disponible (kg)',type:'number'}, {key:'fechaProduccion',label:'Fecha de producción',type:'date'}, {key:'disponibilidad',label:'Disponible para entrega',type:'select',options:['Sí','No']}], sample: [{lote:'LOT-2026-010',cantidad:420,fechaProduccion:'2026-07-15',disponibilidad:'Sí'}, {lote:'LOT-2026-011',cantidad:280,fechaProduccion:'2026-07-22',disponibilidad:'Sí'}] }
};

@Component({ selector: 'app-root', standalone: true, imports: [RouterOutlet], template: '<router-outlet />' })
export class RootComponent {}

@Component({ standalone: true, imports: [CommonModule, FormsModule, ReactiveFormsModule], template: `
<main class="login"><section><div class="brand">♻</div><h1>BioCircular</h1><p>Gestión de recolección y compostaje</p><div class="notice error" *ngIf="error()">{{ error() }}</div><form [formGroup]="form" (ngSubmit)="login()"><label>Correo electrónico</label><input type="email" formControlName="email" placeholder="correo@ejemplo.com"><label>Contraseña</label><input type="password" formControlName="password" placeholder="••••••••"><button type="submit" [disabled]="form.invalid || loading()">{{ loading() ? 'Ingresando…' : 'Iniciar sesión' }}</button></form><a routerLink="/recuperar">¿Olvidaste tu contraseña?</a></section></main>` })
export class LoginComponent {
  private fb = inject(FormBuilder); private http = inject(HttpClient); private router = inject(Router);
  loading = signal(false); error = signal('');
  form = this.fb.nonNullable.group({ email: ['', [Validators.required, Validators.email]], password: ['', Validators.required] });
  login() { if (this.form.invalid) return; this.loading.set(true); this.error.set(''); this.http.post<{accessToken: string}>('/api/auth/login', this.form.getRawValue()).subscribe({ next: r => { localStorage.setItem('jwt', r.accessToken); this.router.navigateByUrl('/dashboard'); }, error: (e: HttpErrorResponse) => { this.loading.set(false); this.error.set(e.status === 0 ? 'No fue posible conectar con el servicio de autenticación.' : 'No se pudo iniciar sesión. Revise sus credenciales.'); } }); }
}

@Component({ standalone: true, imports: [RouterLink], template: `<main class="login"><section><div class="brand">✉</div><h1>Recuperar acceso</h1><p>Ingrese a su correo institucional para solicitar un enlace de recuperación.</p><form><label>Correo electrónico</label><input type="email" placeholder="correo@ejemplo.com"><button type="button">Enviar enlace</button></form><a routerLink="/login">Volver a iniciar sesión</a></section></main>` })
export class RecoveryComponent {}

@Component({ standalone: true, imports: [RouterOutlet, RouterLink, RouterLinkActive, CommonModule], template: `
<header><a class="logo" routerLink="/dashboard">♻ <span>BioCircular</span></a><div class="header-actions"><span class="user">Administrador</span><button class="link-button" (click)="logout()">Cerrar sesión</button></div></header>
<div class="app-shell"><aside><p class="nav-title">OPERACIÓN</p><a routerLink="/dashboard" routerLinkActive="active">Panel general</a><a routerLink="/clientes" routerLinkActive="active">Clientes</a><a routerLink="/contenedores" routerLinkActive="active">Contenedores</a><a routerLink="/rutas" routerLinkActive="active">Rutas</a><a routerLink="/recolecciones" routerLinkActive="active">Recolecciones</a><a routerLink="/vehiculos" routerLinkActive="active">Flota</a><a routerLink="/operadores" routerLinkActive="active">Usuarios y operadores</a><p class="nav-title">COMPOSTAJE</p><a routerLink="/lotes" routerLinkActive="active">Lotes y etapas</a><a routerLink="/residuos" routerLinkActive="active">Tipos de residuos</a><a routerLink="/inventario" routerLinkActive="active">Inventario</a><a routerLink="/trazabilidad" routerLinkActive="active">Trazabilidad</a><p class="nav-title">ANÁLISIS</p><a routerLink="/reportes" routerLinkActive="active">Reportes</a><a routerLink="/indicadores" routerLinkActive="active">Indicadores</a><a routerLink="/auditoria" routerLinkActive="active">Auditoría</a><a routerLink="/perfil" routerLinkActive="active">Mi perfil</a></aside><main class="content"><router-outlet /></main></div>` })
export class ShellComponent { private router = inject(Router); logout() { localStorage.removeItem('jwt'); this.router.navigateByUrl('/login'); } }

@Component({ standalone: true, imports: [CommonModule, RouterLink], template: `
<div class="page-head"><div><p class="eyebrow">VISTA GENERAL</p><h1>Dashboard operativo</h1><p>Resumen de la operación y del impacto ambiental.</p></div><a class="button secondary" routerLink="/reportes">Ver reportes</a></div>
<section class="cards"><article><span>Clientes activos</span><b>248</b><small>+12 este mes</small></article><article><span>Recolecciones hoy</span><b>34</b><small>Meta diaria: 40</small></article><article><span>Residuos recolectados</span><b>1.28 t</b><small>En los últimos 7 días</small></article><article><span>Compost disponible</span><b>700 kg</b><small>Listo para entrega</small></article></section>
<section class="two-columns"><article class="panel"><h2>Próximas rutas</h2><div class="list-row"><b>Ruta Norte 01</b><span>08:00 · Carlos Pérez</span><em>En curso</em></div><div class="list-row"><b>Ruta Centro 02</b><span>10:30 · Ana Mena</span><em>Programada</em></div></article><article class="panel"><h2>Alertas operativas</h2><div class="alert warning">1 vehículo requiere mantenimiento.</div><div class="alert success">Lote LOT-2026-010 finalizó correctamente.</div></article></section>` })
export class DashboardComponent {}

@Component({ standalone: true, imports: [CommonModule, FormsModule, ReactiveFormsModule], template: `
<div class="page-head"><div><p class="eyebrow">GESTIÓN</p><h1>{{ config.title }}</h1><p>{{ config.subtitle }}</p></div><button (click)="openCreate()">+ Nuevo registro</button></div>
<div class="toolbar"><input [(ngModel)]="query" (input)="filter()" placeholder="Buscar por cualquier dato…"><span>{{ filtered().length }} registros</span></div>
<div class="panel table-wrap"><table><thead><tr><th *ngFor="let col of config.columns">{{ label(col) }}</th><th>Acciones</th></tr></thead><tbody><tr *ngFor="let row of filtered()"><td *ngFor="let col of config.columns">{{ row[col] || '—' }}</td><td class="actions"><button class="icon-button" (click)="edit(row)">Editar</button><button class="icon-button danger" (click)="remove(row)">Dar de baja</button></td></tr><tr *ngIf="!filtered().length"><td [attr.colspan]="config.columns.length + 1">No hay registros que coincidan con la búsqueda.</td></tr></tbody></table></div>
<div class="modal-backdrop" *ngIf="editing"><section class="modal"><div class="modal-head"><h2>{{ selected ? 'Editar' : 'Nuevo' }} {{ config.title.slice(0, -1) }}</h2><button class="icon-button" type="button" (click)="close()">Cerrar</button></div><form [formGroup]="form" (ngSubmit)="save()"><label *ngFor="let f of config.fields">{{ f.label }}<select *ngIf="f.type === 'select'" [formControlName]="f.key"><option value="">Seleccione…</option><option *ngFor="let o of f.options" [value]="o">{{ o }}</option></select><textarea *ngIf="f.type === 'textarea'" [formControlName]="f.key"></textarea><input *ngIf="f.type !== 'select' && f.type !== 'textarea'" [type]="f.type || 'text'" [formControlName]="f.key"></label><div class="modal-actions"><button class="secondary" type="button" (click)="close()">Cancelar</button><button type="submit" [disabled]="form.invalid">Guardar registro</button></div></form></section></div>` })
export class CrudComponent {
  private fb = inject(FormBuilder); private router = inject(Router);
  config = MODULES[this.router.url.split('/')[1]] ?? MODULES.clientes; rows = signal([...this.config.sample]); filtered = signal([...this.config.sample]); editing = false; selected: Record<string, string | number> | null = null; query = '';
  form = this.fb.group(Object.fromEntries(this.config.fields.map(f => [f.key, ['', Validators.required]])));
  label(key: string) { return this.config.fields.find(f => f.key === key)?.label ?? key; }
  filter() { const q = this.query.toLocaleLowerCase(); this.filtered.set(this.rows().filter(r => Object.values(r).some(v => String(v).toLocaleLowerCase().includes(q)))); }
  openCreate() { this.selected = null; this.form.reset(); this.editing = true; }
  edit(row: Record<string, string | number>) { this.selected = row; this.form.reset(Object.fromEntries(Object.entries(row).map(([key, value]) => [key, String(value)]))); this.editing = true; }
  close() { this.editing = false; }
  save() { if (this.form.invalid) return; const value = this.form.getRawValue() as Record<string, string | number>; this.rows.set(this.selected ? this.rows().map(r => r === this.selected ? value : r) : [value, ...this.rows()]); this.filter(); this.close(); }
  remove(row: Record<string, string | number>) { if (confirm('¿Confirma que desea dar de baja este registro?')) { this.rows.set(this.rows().filter(r => r !== row)); this.filter(); } }
}

@Component({ standalone: true, imports: [CommonModule, ReactiveFormsModule], template: `
<div class="page-head"><div><p class="eyebrow">CONSULTA</p><h1>{{ title }}</h1><p>{{ description }}</p></div></div><section class="panel filters"><label>Desde<input type="date"></label><label>Hasta<input type="date"></label><label>Sector<select><option>Todos los sectores</option><option>Norte</option><option>Centro</option></select></label><button>Aplicar filtros</button></section><section class="panel" *ngIf="kind === 'reportes'"><h2>Reportes disponibles</h2><div class="report-row" *ngFor="let r of reports"><div><b>{{ r }}</b><p>Información filtrada y lista para exportar.</p></div><div><button class="secondary">Vista previa</button><button>PDF</button><button>Excel</button></div></div></section><section class="cards" *ngIf="kind === 'indicadores'"><article><span>Residuos del período</span><b>8.4 t</b><small>+9 % frente al período anterior</small></article><article><span>Compost producido</span><b>2.1 t</b><small>25 % de aprovechamiento</small></article><article><span>Rutas completadas</span><b>97 %</b><small>63 de 65 programadas</small></article><article><span>CO₂ evitado</span><b>1.7 t</b><small>Estimación ambiental</small></article></section><section class="panel" *ngIf="kind === 'auditoria'"><h2>Actividad reciente</h2><div class="list-row" *ngFor="let a of audit"><b>{{ a.action }}</b><span>{{ a.detail }}</span><em>{{ a.date }}</em></div></section>` })
export class AnalysisComponent { private router = inject(Router); kind = this.router.url.split('/')[1]; title = this.kind === 'reportes' ? 'Centro de reportes' : this.kind === 'indicadores' ? 'Indicadores ambientales' : 'Auditoría'; description = this.kind === 'reportes' ? 'Filtre, consulte y descargue informes en PDF o Excel.' : this.kind === 'indicadores' ? 'Mida el impacto ambiental y el desempeño operativo.' : 'Revise las acciones relevantes realizadas en la plataforma.'; reports = ['Recolecciones por cliente', 'Operación por ruta y operador', 'Proceso de compostaje', 'Inventario disponible']; audit = [{action:'Recolección registrada',detail:'Carlos Pérez · Eco Mercado Central',date:'Hoy, 09:32'}, {action:'Lote actualizado',detail:'Ana Mena · LOT-2026-014',date:'Hoy, 08:10'}, {action:'Cliente editado',detail:'Administrador · María López',date:'Ayer, 16:45'}]; }

@Component({ standalone: true, imports: [CommonModule], template: `<div class="page-head"><div><p class="eyebrow">SEGUIMIENTO</p><h1>Trazabilidad de lote</h1><p>Consulte el recorrido desde la recolección hasta el compost final.</p></div><button>Buscar lote</button></div><section class="panel"><label>Seleccione un lote <select><option>LOT-2026-014</option><option>LOT-2026-015</option></select></label><div class="timeline"><div><b>1. Recolección</b><span>08 jul. · Ruta Norte 01 · 1.220 kg</span></div><div><b>2. Recepción</b><span>10 jul. · Ingreso validado en planta</span></div><div><b>3. Descomposición</b><span>17 jul. · Temperatura y humedad registradas</span></div><div class="current"><b>4. Maduración</b><span>Actualizado hoy · Responsable: Ana Mena</span></div></div></section>` })
export class TraceabilityComponent {}

@Component({ standalone: true, imports: [ReactiveFormsModule], template: `<div class="page-head"><div><p class="eyebrow">CUENTA</p><h1>Mi perfil</h1><p>Actualice sus datos y contraseña de acceso.</p></div></div><section class="panel profile"><h2>Información personal</h2><label>Nombres<input value="Administrador BioCircular"></label><label>Correo<input type="email" value="admin@biocircular.ec"></label><label>Cargo<input value="Administrador"></label><button>Guardar cambios</button><hr><h2>Cambiar contraseña</h2><label>Contraseña actual<input type="password"></label><label>Nueva contraseña<input type="password"></label><label>Confirmar contraseña<input type="password"></label><button>Actualizar contraseña</button></section>` })
export class ProfileComponent {}

const childRoutes: Routes = [{path:'dashboard',component:DashboardComponent}, ...Object.keys(MODULES).map(path => ({path,component:CrudComponent})), {path:'trazabilidad',component:TraceabilityComponent}, {path:'reportes',component:AnalysisComponent}, {path:'indicadores',component:AnalysisComponent}, {path:'auditoria',component:AnalysisComponent}, {path:'perfil',component:ProfileComponent}, {path:'',pathMatch:'full',redirectTo:'dashboard'}];
const routes: Routes = [{path:'login',component:LoginComponent}, {path:'recuperar',component:RecoveryComponent}, {path:'',component:ShellComponent,children:childRoutes}, {path:'**',redirectTo:'dashboard'}];
bootstrapApplication(RootComponent, {providers: [provideRouter(routes), provideHttpClient(withInterceptors([authInterceptor]))]});
