server {
  listen 80;
  server_name _;
  root /usr/share/nginx/html;
  index index.html;

  location /api/auth/ {
    proxy_pass http://auth-service:8080;
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
  }

  location ~ ^/api/(clientes|contenedores|operadores|vehiculos|rutas|recolecciones)$ {
    proxy_pass http://gestion-service:8080;
    proxy_set_header Host $host;
  }

  location ~ ^/api/(tipos-residuos|ingresos-residuos|lotes|etapas-lote|compost|inventario|trazabilidad|dashboard) {
    proxy_pass http://compostaje-service:8080;
    proxy_set_header Host $host;
  }

  location /api/reportes/ { proxy_pass http://reportes-service:8080; }
  location /api/auditoria/ { proxy_pass http://auditoria-service:8080; }
  location /api/notificaciones/ { proxy_pass http://notificaciones-service:8080; }
  location /api/monitoring/ { proxy_pass http://monitoring-service:8080; }

  location / {
    try_files $uri $uri/ /index.html;
  }
}
