# Puerto Gateway
server.port=8080

spring.application.name=api-gateway

# AUTH
spring.cloud.gateway.routes[0].id=auth-service
spring.cloud.gateway.routes[0].uri=http://auth-service:8081
spring.cloud.gateway.routes[0].predicates[0]=Path=/auth/**

# GESTION
spring.cloud.gateway.routes[1].id=gestion-service
spring.cloud.gateway.routes[1].uri=http://gestion-service:8082
spring.cloud.gateway.routes[1].predicates[0]=Path=/gestion/**
spring.cloud.gateway.routes[1].filters[0]=StripPrefix=1

# COMPOSTAJE
spring.cloud.gateway.routes[2].id=compostaje-service
spring.cloud.gateway.routes[2].uri=http://compostaje-service:8083
spring.cloud.gateway.routes[2].predicates[0]=Path=/compostaje/**
spring.cloud.gateway.routes[2].filters[0]=StripPrefix=1